GET http://localhost:3000/api/users

###
GET http://localhost:3000/api/users/64aab4f80c19334d28431145

###
POST http://localhost:3000/api/users/newUser
Content-Type: application/json

{
    "name": "Dwayne Johnson",
    "email": "256ham@yahoo.com"
}

###
DELETE http://localhost:3000/api/users/64aab4f80c19334d28431145

###
PUT http://localhost:3000/api/updateUser/64aac10f4fda01d9077b1358
Content-Type:application/json

{
    "name": "New Name"
}

###
PUT http://localhost:3000/api/users
Content-Type: application/json

{
    "thought":"Lets roll out!",
    "username": "Bumblebee"
}

###
GET http://localhost:3000/api/users/thoughts