GET http://localhost:3000/api/users

###
GET http://localhost:3000/api/users/64acb6eb628455426292e54c

###
POST http://localhost:3000/api/users/newUser
Content-Type: application/json

{
    "name": "Wendell Fowlkes",
    "email": "321turkey@yahoo.com"
}

###
DELETE http://localhost:3000/api/users/64ed01b78bdbfd265ae4b26c

###
PUT http://localhost:3000/api/users/64bc0ee773c778dc4dbc0a01
Content-Type:application/json

{
    "name": "The Rock"
}

###
POST http://localhost:3000/api/users/
Content-Type: application/json

{
    "id":"64aab36ee9b5e2c4c8d46c09",
    "thought": "I know nothing."
}

###
GET http://localhost:3000/api/users/64acb6eb628455426292e54c/thoughts