GET http://localhost:3000/users

###
GET http://localhost:3000/64aab36ee9b5e2c4c8d46c09

###
POST http://localhost:3000/
Content-Type: application/json

{
    "name": "Mack Johnson",
    "email": "296ham@yahoo.com"
}

###
DELETE http://localhost:3000/deleteUser/64aaca6106f398a299740319

###
PUT http://localhost:3000/updateUser/64aac10f4fda01d9077b1358
Content-Type:application/json

{
    "name": "New Name"
}

###
PUT http://localhost:3000/users/new-thought
Content-Type: application/json

{
    "thought":"This is a new thought!",
    "username": "Huey Freeman"
}

###
GET http://localhost:3000/users/thoughts